### PR TITLE
Implement sort pushdown.

### PR DESCRIPTION
**Pull request by rjuju**
Hello,

This patch implements sort pushdown for multicorn.

As I'm not really familiar with C-Python API, there's probably some Py_DECREF() missing, or maybe some other issues. Let me know if I can help to fix any problem remaning.

Many thanks to Ronan Dunklau for helping with the general design and a lot of issues :)

Regards.

### CODE REVIEW

**Comment by rdunklau** [comment]
A few comments about this PR:

 - the patch reverts the requirements to python2.7, although work as recently been contributed to have compatibility with python2.6. Any reason for that ? Generally, it looks like some patches have been reverted. Could you please take a look at that, rebasing on the latest master ?
 - some code seem to have been modified for no good reason: eg, the processfdw module.
- I know for a fact you wrote tests, why not include them in the PR ? :)

About the code itself: 
- the MulticornSortKey should be renamed to SortKey, since it already lives in a multicorn module.
- the documentation in __init__.py refers to MulticornSortKey instances as MulticornDeparsedSortGroup instances, which is the C-struct name
 - the testfdw class is using convoluted string concatenations to dump the path_keys arguments. It should be better to implement that in a __repr__ method of MulticornSortKey
 - the testfdw fails to account for when it returns list instead of dicts (see the test_type = 'sequence' code path).
 - the EXPLAIN code path should better either be left as it was, or implemented properly through a callback to the python API.
 - the path keys are not properly serialized / deserialized. This results in a SEGFAULT whenever the need for portals arise, eg: 
DECLARE t1 SCROLL CURSOR FOR  SELECT * FROM testmulticorn order by test1 desc;
ERROR:  unrecognized node type: 1953719668
- I don't understand why no paths are generated for (sorted) parameterized pathes. Shouldn't it be beneficial, so as to allow mergejoin in certain cases ?

I'll check the reference counts later on, but this is a very promising patch, with minor issues to work on.

**Comment by rjuju** [comment]
Yes, I just noticed that I didn't rebase the patch on the latest commit. I'll rebase it.

For the processfdw file, I noticed the file was in dos fileformat, and I changed it to unix. I'll exclude that from the PR.

I simply forgot to add the files for the new tests :) commit ba903c3 fixes that.

I'll work on the other issues as soon as I'll have a proper rebase. Thanks!

**Comment by rjuju** [comment]
All the problems in the initial pull request should now be corrected. The collation is also now always specified (instead of a simple "default").

**Comment by jmealo** [comment]
@rdunklau @rjuju: Great collaboration on this PR. Any chance on this getting merged/closed?

**Comment by rjuju** [comment]
@jmealo thanks! The feature has been merged in a single commit (https://github.com/Kozea/Multicorn/commit/9dd1208f4a50573e4b3aee46e6628733745cb614) instead of this PR to keep history clean.  We should have mentioned it here :/

This is available since release 1.3.0

**Comment by oscardssmith** [comment]
This should probably be closed now that it is merged.

**Comment by rjuju** [comment]
Indeed, sorry I didn't do it earlier.

Merged in https://github.com/Kozea/Multicorn/commit/9dd1208f4a50573e4b3aee46e6628733745cb614

**Pull request closed without merging**
