### PR TITLE
Update for PostgreSQL v11

### PR DESCRIPTION
**Pull request by jeffjanes**
The old way of accessing attributes has finally been removed
in favor of TupleDescAttr, so change the code to use that
macro.  This macro exists back to 9.2.

This fixes issue #206.

### CODE REVIEW

**Comment by galuszkak** [comment]
Hey @rdunklau @rdunklau-4ct @rvernica,

It would be great if this can be merged as PostgreSQL 11 is with us for some time.

Thanks for hard work!

**Comment by bernochoa** [comment]
Unfortunately, I believe the Kozea folks have stopped giving a damn about this project and abandoned it, as they haven't done anything about it or replied to requests for well over a year now. I wish they would give collaborator access to people keen on maintaining it before the project rots away.

**Comment by liZe** [comment]
> Unfortunately, I believe the Kozea folks have stopped giving a damn about this project and abandoned it, as they haven't done anything about it or replied to requests for well over a year now.

We've not abandoned it (we use it in production), but it's true that we don't spend time on this project anymore.

> I wish they would give collaborator access to people keen on maintaining it before the project rots away.

Anyone intested? :smile:

**Comment by galuszkak** [comment]
@liZe I'm interested to help here with maintenance.

**Comment by liZe** [comment]
> @liZe I didn't event know we had a Multicorn organization :) Maybe we should move the repo to that namespace as a first step ?

Hi :smile:! It's not an organization, it's a team. If anyone wants to create a separate organization, there's no problem to move the repository.

**Comment by galuszkak** [comment]
@liZe @rdunklau let's move that discussion to maybe another issue, I will merge this PR as sounds it's fixing issue with PostgreSQL 11.

**Comment by galuszkak** [comment]
Moved discussion to #221

**Pull request merged**
